[project]
name = "expresate"
version = "0.1.0"
description = "our testing labs for the expresate project"
readme = "readme.md"
requires-python = ">=3.13,<3.14"

[tool.uv.workspace]
members = ["smv", "policia", "dbf"]
